channels:
  - conda-forge
dependencies:
  - jupyterlab
  - python=3.8
  - ipywidgets=7.6
  - ipympl=0.7
  - watermark=2.2
  - numpy=1.20
  - scipy=1.6
  - matplotlib=3.4
  - pandas=1.2
  - xarray=0.17
  - gdal=3.2
  - cartopy=0.18
  - holoviews=1.14
  - geoviews=1.9
  - hvplot=0.7
  - pooch=1.3
  - pip:
    - viresclient
    - chaosmagpy==0.6
