on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run:
    name: Build Jupyter Book
    runs-on: ubuntu-latest
    steps:
      - name: Pull docker image
        run: |
          echo ${{ secrets.EOX_REGISTRY_PASSWORD }} | docker login -u ${{ secrets.EOX_REGISTRY_USER }} --password-stdin registry.gitlab.eox.at
          docker pull registry.gitlab.eox.at/esa/vires_vre_ops/vre-swarm-notebook:0.8.0
      - uses: actions/checkout@v2
      - name: Execute notebooks and build book
        run: |
          docker run -v $GITHUB_WORKSPACE:/home/jovyan -u root \
            -e VIRES_TOKEN=${{ secrets.VIRES_TOKEN }} \
            registry.gitlab.eox.at/esa/vires_vre_ops/vre-swarm-notebook:0.8.0 \
            bash -c \
              '
              viresclient set_token https://vires.services/ows $VIRES_TOKEN && \
              viresclient set_default_server https://staging.vires.services/ows && \
              pip install 'jupyter-book==0.11.*' && \
              jupyter-book build .
              '
      - name: Deploy preview with netlify
        run: netlify deploy --dir=_build/html --auth=${{ secrets.NETLIFY_AUTH_TOKEN }} --site=${{ secrets.NETLIFY_SITE_API_ID }}
